language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
gemfile:
  - Gemfile
script: ./script/ci/run_build.sh
install: bundle install --deployment && cd example && bundle install --deployment
branches:
  only:
    - master
