language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
gemfile:
  - Gemfile
script:
  - bundle exec rake
  - cd example && bundle exec rake docs:generate
install: bundle install --deployment && pushd example && bundle install --deployment && popd
branches:
  only:
    - master
